# Generated by Django 5.1.1 on 2024-09-12 06:14

import django.db.models.deletion
import libs.truncate_table_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('interval', models.PositiveIntegerField(verbose_name='Интервал (в секундах)')),
            ],
            options={
                'verbose_name': 'Интервал рассылки',
                'verbose_name_plural': 'интервалы рассылки',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('pk',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время')),
                ('execution_time', models.PositiveIntegerField(default=120, verbose_name='Время выполнения, в секундах')),
                ('is_publiс', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.action', verbose_name='Действие')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.dateperiod', verbose_name='Периодичность')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('-pk',),
                'unique_together': {('location', 'action', 'time')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pleasant_habit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useful_habits', to='habit.habit', verbose_name='Приятная привычка')),
                ('reward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useful_habits', to='habit.reward', verbose_name='Вознаграждение')),
            ],
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserPleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pleasant_habits', to='habit.habit', verbose_name='Приятная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pleasant_habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserUsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.usefulhabit', verbose_name='Полезная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
    ]
