# Generated by Django 5.1.1 on 2024-09-12 09:44

import django.db.models.deletion
import libs.truncate_table_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('interval', models.PositiveIntegerField(unique=True, verbose_name='Интервал (в секундах)')),
            ],
            options={
                'verbose_name': 'Интервал рассылки',
                'verbose_name_plural': 'интервалы рассылки',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('pk',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время')),
                ('execution_time', models.PositiveIntegerField(default=120, verbose_name='Время выполнения, в секундах')),
                ('is_publiс', models.BooleanField(default=False, verbose_name='Общедоступный')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.action', verbose_name='Действие')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.dateperiod', verbose_name='Периодичность')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.location', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('-pk',),
                'unique_together': {('location', 'action', 'time', 'periodicity', 'execution_time', 'is_publiс')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_habits', to='habit.habit', unique=True, verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.habit', verbose_name='Привычка')),
                ('pleasant_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.pleasanthabit', verbose_name='Приятная привычка')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.reward', verbose_name='Вознаграждение')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
                'unique_together': {('habit', 'pleasant_habit', 'reward')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
    ]
