# Generated by Django 5.1.1 on 2024-09-15 00:27

import django.db.models.deletion
import libs.manual_model_saving_mixin
import libs.truncate_table_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('interval', models.PositiveIntegerField(unique=True, verbose_name='Интервал (в секундах)')),
            ],
            options={
                'verbose_name': 'Периодичность',
                'verbose_name_plural': 'Периодичности',
                'ordering': ('pk',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятного действия')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ('pk',),
                'unique_together': {('name', 'is_pleasant')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('execution_time', models.PositiveIntegerField(default=120, verbose_name='Время выполнения, в секундах')),
                ('is_publiс', models.BooleanField(default=False, verbose_name='Общедоступность')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.action', verbose_name='Действие')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.location', verbose_name='Место')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.periodicity', verbose_name='Периодичность')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('pk',),
                'unique_together': {('location', 'action', 'time')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, libs.manual_model_saving_mixin.ManualModelSavingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_habits', to='habit.habit', verbose_name='Привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
                'ordering': ('pk',),
                'unique_together': {('user', 'habit')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, libs.manual_model_saving_mixin.ManualModelSavingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.habit', verbose_name='Привычка')),
                ('pleasant_habit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.pleasanthabit', verbose_name='Приятная привычка')),
                ('reward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.reward', verbose_name='Вознаграждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
                'ordering': ('pk',),
                'unique_together': {('user', 'habit')},
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, libs.manual_model_saving_mixin.ManualModelSavingMixin, models.Model),
        ),
    ]
