# Generated by Django 5.1.1 on 2024-09-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasanthabit',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_habits', to='habit.habit', verbose_name='Привычка'),
        ),
    ]
