# Generated by Django 5.1.1 on 2024-09-13 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('location', 'action', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='usefulhabit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userful_habit', to='habit.habit', verbose_name='Привычка'),
        ),
        migrations.AlterUniqueTogether(
            name='usefulhabit',
            unique_together={('author', 'habit')},
        ),
    ]
