# Generated by Django 5.1.1 on 2024-09-13 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='pleasant_habit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.pleasanthabit', verbose_name='Приятная привычка'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='reward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.reward', verbose_name='Вознаграждение'),
        ),
    ]
