# Generated by Django 5.1.1 on 2024-09-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_pleasanthabit_habit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('pk',), 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterModelOptions(
            name='pleasanthabit',
            options={'ordering': ('pk',), 'verbose_name': 'Приятная привычка', 'verbose_name_plural': 'Приятные привычки'},
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='pleasant_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.pleasanthabit', verbose_name='Приятная привычка'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userful_habits', to='habit.reward', verbose_name='Вознаграждение'),
        ),
    ]
