# Generated by Django 5.1.1 on 2024-09-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_is_publiс'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Приятное'),
        ),
    ]
