# Generated by Django 5.1.1 on 2024-09-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasanthabit',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_habits', to='habit.habit', verbose_name='Привычка'),
        ),
    ]
