# Generated by Django 5.1.1 on 2024-09-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_action_is_pleasant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('pk',), 'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
        migrations.AlterField(
            model_name='action',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='приятное'),
        ),
    ]
