# Generated by Django 5.1.1 on 2024-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_action_options_alter_action_is_pleasant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
